services:
  excalidraw:
    build:
      context: .
      dockerfile: Dockerfile
    image: excalidraw-file-manager:latest
    container_name: excalidraw-file-manager
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      PORT: "8088"
      EXCALIDRAW_WORKSPACE_DIR: /opt/excalidraw/workspace
      EXCALIDRAW_USERNAME: fanmd
      EXCALIDRAW_PASSWORD: "123123"
    volumes:
      - /opt/excalidraw/workspace:/opt/excalidraw/workspace
